#!/bin/bash

set -euo pipefail

cd "$(dirname "$0")/.."

OUTPUT_PATH="${OUTPUT_PATH:-Configuration/custom.xcconfig}"
VERSION=""
BUILD_NUMBER=""
DEVELOPMENT_TEAM_VALUE="${DEVELOPMENT_TEAM:-}"
SIGNING_IDENTITY_VALUE="${SIGNING_IDENTITY:-}"
PRODUCT_BUNDLE_IDENTIFIER_VALUE="${PRODUCT_BUNDLE_IDENTIFIER:-}"

usage() {
	cat <<'EOF'
Usage: bash Scripts/write-github-action-xcconfig.sh --version <x.y.z> --build-number <n> [options]

Options:
  --version <x.y.z>          MARKETING_VERSION value. Accepts an optional leading v.
  --build-number <n>         CURRENT_PROJECT_VERSION value.
  --development-team <id>    DEVELOPMENT_TEAM override.
  --signing-identity <name>  CODE_SIGN_IDENTITY override.
  --bundle-id <id>           PRODUCT_BUNDLE_IDENTIFIER override.
  --output <path>            Output xcconfig path. Default: Configuration/custom.xcconfig.
  --help, -h                 Show this help.
EOF
}

fail() {
	echo "Error: $*" >&2
	exit 1
}

normalize_version() {
	local raw="$1"
	raw="${raw#refs/tags/}"
	raw="${raw#v}"
	[[ "$raw" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || fail "Invalid version '$1'. Expected x.y.z or vX.Y.Z."
	echo "$raw"
}

parse_args() {
	while [[ $# -gt 0 ]]; do
		case "$1" in
		--version)
			VERSION="$(normalize_version "${2:-}")"
			shift 2
			;;
		--build-number)
			BUILD_NUMBER="${2:-}"
			shift 2
			;;
		--development-team)
			DEVELOPMENT_TEAM_VALUE="${2:-}"
			shift 2
			;;
		--signing-identity)
			SIGNING_IDENTITY_VALUE="${2:-}"
			shift 2
			;;
		--bundle-id)
			PRODUCT_BUNDLE_IDENTIFIER_VALUE="${2:-}"
			shift 2
			;;
		--output)
			OUTPUT_PATH="${2:-}"
			shift 2
			;;
		--help | -h)
			usage
			exit 0
			;;
		*)
			fail "Unknown option: $1"
			;;
		esac
	done
}

write_setting() {
	local key="$1"
	local value="$2"
	[[ -n "$value" ]] || return 0
	printf '%s = %s\n' "$key" "$value"
}

parse_args "$@"

[[ -n "$VERSION" ]] || fail "--version is required."
[[ -n "$BUILD_NUMBER" ]] || fail "--build-number is required."
[[ "$BUILD_NUMBER" =~ ^[0-9]+$ ]] || fail "Invalid build number '$BUILD_NUMBER'. Expected an integer."

mkdir -p "$(dirname "$OUTPUT_PATH")"

{
	echo "// Generated by Scripts/write-github-action-xcconfig.sh"
	echo "// This file is ignored by git."
	echo
	write_setting MARKETING_VERSION "$VERSION"
	write_setting CURRENT_PROJECT_VERSION "$BUILD_NUMBER"
	write_setting DEVELOPMENT_TEAM "$DEVELOPMENT_TEAM_VALUE"
	write_setting PRODUCT_BUNDLE_IDENTIFIER "$PRODUCT_BUNDLE_IDENTIFIER_VALUE"
	write_setting CODE_SIGN_IDENTITY "$SIGNING_IDENTITY_VALUE"
} >"$OUTPUT_PATH"

echo "Wrote $OUTPUT_PATH"
